a = "Traceback (most recent call last):\n  File \"./pylib/ffext.py\", line 118, in ff_session_verify\n    ret = g_session_verify_callback(session_key, online_time, ip, gate_name, cb_id)\n  File \"./pyproject/login/login_mgr.py\", line 98, in real_session_verify\n    assert False\nAssertionError\nDetail:\n Current dump time: 2017-05-28 05:50:48\n /home/jhfeng/Documents/red_rabbit/pyproject/login/login_mgr.py in real_session_verify(szAuthKey='\\x08\\x02\\x12\\x05acc_0', online_time=1495921848L, ip='127.0.0.1', gate_name='gate@0', cb_id=1)\n    96         return []\n    97 \n    98     assert False\n    99 \n   100     print(\"real_session_verify \", szAuthKey, online_time, ip, gate_name, cb_id)\n Local Var:\n    cb_id = 1\n    gate_name = 'gate@0'\n    szAuthKey = '\\x08\\x02\\x12\\x05acc_0'\n    online_time = 1495921848L\n    ip = '127.0.0.1'\n    builtinFalse = False\n"
print(a)