21:42:34.146 TRACE [32378] [FFSCENE_PYTHON] ffscene_python_t::open begin
21:42:34.391 TRACE [32378] [FFSCENE] ffscene_t::open begin
21:42:34.392 INFO  [32378] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
21:42:34.392 TRACE [32378] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[12] begin
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::open end ok m_node_id[12]
21:42:34.393 TRACE [32378] [FFSCENE] ffscene_t::open end ok
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[6],bind_broker_id[0]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[12],bind_broker_id[0]
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
21:42:34.393 TRACE [32378] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
21:42:34.393 TRACE [32378] [FFSCENE_PYTHON] ffscene_python_t::open end ok
21:42:36.633 TRACE [32378] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:42:36.633 TRACE [32378] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[1] begin
21:42:36.633 TRACE [32378] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:42:36.638 ERROR [32378] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<param[1] type invalid, string needed
Traceback (most recent call last):

  File "./pylib/ffext.py", line 94, in ff_session_verify
    ret = g_session_verify_callback(session_key, online_time, ip, gate_name)

  File "./pyproject/player_mgr/player_mgr_handler.py", line 11, in real_session_verify
    session_id = dbservice.get_session_by_auth_key(szAuthKey)

  File "./pyproject/db/dbservice.py", line 33, in get_session_by_auth_key
    import id_manager.idmanager as idmgr

  File "./pyproject/id_manager/idmanager.py", line 60, in <module>
    _PlayerIDMgr.init()

  File "./pyproject/id_manager/idmanager.py", line 14, in init
    self.db = ffext.ffdb_create(self.db_host)

  File "./pylib/ffext.py", line 239, in ffdb_create
    db_id = ff.ffscene_obj.connect_db(host_)

  File "<string>", line 48, in connect_db

TypeError: param[1] type invalid, string needed

>
21:42:36.638 TRACE [32378] [FFSCENE] ffscene_t::process_session_verify end ok
21:42:36.638 INFO  [32378] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:42:36.638 TRACE [32378] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:42:36.638 INFO  [32378] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:42:36.638 TRACE [32378] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[1] end ok
