23:10:30.017 TRACE [3820] [FFSCENE_PYTHON] ffscene_python_t::open begin
23:10:30.023 TRACE [3820] [FFSCENE] ffscene_t::open begin
23:10:30.023 INFO  [3820] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[6] begin
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[6],bind_broker_id[0]
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
23:10:30.024 TRACE [3820] [FFRPC] ffrpc_t::open end ok m_node_id[6]
23:10:30.025 TRACE [3820] [FFSCENE] ffscene_t::open end ok
23:10:30.025 TRACE [3820] [FFSCENE_PYTHON] ffscene_python_t::open end ok
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[0] begin
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[6],bind_broker_id[0]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[12],bind_broker_id[0]
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
23:10:30.239 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
23:10:32.625 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:10:32.625 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[3] begin
23:10:32.625 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:10:32.631 ERROR [3820] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<'NoneType' object has no attribute 'flag'
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 22, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 75, in load_player
    if ret.flag is False:

AttributeError: 'NoneType' object has no attribute 'flag'

>
23:10:32.632 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter end ok
23:10:32.632 INFO  [3820] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:10:32.633 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:10:32.633 INFO  [3820] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:10:32.635 TRACE [3820] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[3] end ok
23:12:05.400 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:12:05.401 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[6] begin
23:12:05.401 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:12:05.401 ERROR [3820] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<'NoneType' object has no attribute 'flag'
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 22, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 75, in load_player
    if ret.flag is False:

AttributeError: 'NoneType' object has no attribute 'flag'

>
23:12:05.401 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter end ok
23:12:05.401 INFO  [3820] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:12:05.401 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:12:05.401 INFO  [3820] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:12:05.401 TRACE [3820] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[6] end ok
23:12:11.242 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:12:11.242 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[9] begin
23:12:11.242 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:12:11.242 ERROR [3820] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<'NoneType' object has no attribute 'flag'
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 22, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 75, in load_player
    if ret.flag is False:

AttributeError: 'NoneType' object has no attribute 'flag'

>
23:12:11.242 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter end ok
23:12:11.242 INFO  [3820] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:12:11.242 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:12:11.243 INFO  [3820] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:12:11.243 TRACE [3820] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[9] end ok
23:12:20.317 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:12:20.317 TRACE [3820] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[12] begin
23:12:20.317 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:12:20.317 ERROR [3820] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<'NoneType' object has no attribute 'flag'
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 22, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 75, in load_player
    if ret.flag is False:

AttributeError: 'NoneType' object has no attribute 'flag'

>
23:12:20.317 TRACE [3820] [FFSCENE] ffscene_t::process_session_enter end ok
23:12:20.317 INFO  [3820] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:12:20.317 TRACE [3820] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:12:20.317 INFO  [3820] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:12:20.317 TRACE [3820] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[12] end ok
