21:48:07.879 TRACE [317] [FFSCENE_PYTHON] ffscene_python_t::open begin
21:48:08.132 TRACE [317] [FFSCENE] ffscene_t::open begin
21:48:08.132 INFO  [317] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
21:48:08.135 TRACE [317] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[12] begin
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[6],bind_broker_id[0]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[12],bind_broker_id[0]
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
21:48:08.136 TRACE [317] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
21:48:08.137 TRACE [317] [FFRPC] ffrpc_t::open end ok m_node_id[12]
21:48:08.138 TRACE [317] [FFSCENE] ffscene_t::open end ok
21:48:08.138 TRACE [317] [FFSCENE_PYTHON] ffscene_python_t::open end ok
21:48:10.084 TRACE [317] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:48:10.084 TRACE [317] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[1] begin
21:48:10.084 TRACE [317] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:48:10.087 ERROR [317] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<value returned is not vector ff_session_verify in ffext>
21:48:10.087 TRACE [317] [FFSCENE] ffscene_t::process_session_verify end ok
21:48:10.087 INFO  [317] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:48:10.087 TRACE [317] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:48:10.087 INFO  [317] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:48:10.087 TRACE [317] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[1] end ok
21:49:15.696 TRACE [317] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
21:49:15.697 TRACE [317] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[11],callback_id[2] begin
21:49:15.697 TRACE [317] [FFSCENE] ffscene_t::process_session_verify begin session_key size=6
21:49:15.697 ERROR [317] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<value returned is not vector ff_session_verify in ffext>
21:49:15.697 TRACE [317] [FFSCENE] ffscene_t::process_session_verify end ok
21:49:15.697 INFO  [317] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
21:49:15.697 TRACE [317] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
21:49:15.697 INFO  [317] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
21:49:15.697 TRACE [317] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[2] end ok
